services:
  db:
    image: postgres:15
    container_name: mobility-db
    restart: always
    environment:
      POSTGRES_USER: user_mobility
      POSTGRES_PASSWORD: password_mobility
      POSTGRES_DB: mobility_db
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: mobility-container-final
    restart: always
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://user_mobility:password_mobility@db:5432/mobility_db
    ports:
      - "8000:8000"
    depends_on:
      - db
